language: java

env:
  global:
    # SONATYPE_USERNAME
    - secure: "YG/IQW1hZqTXmz66fDmUtX6lvbqrwLBhD/kuHsgWdG0NolkpRuAOxlMno71wuWmJx82y0BOiryE27cOTMv4/znz47+nyfpo1PIq7CyUxNv4uUlBEqfmSegHlb2Z2Lr4bziNELjAOTF3N3JfWn8sQfBEaqZ8DQGgl0Cp3foC6AcVh2Ffccv7zt11dn1DWla+xUwIJDAunXL3jlavgeqSkkgbc8M+YVGV/oGwdzP3dyW2e/aklIgXhJaBsNOQyZRZn+d9vNYfyKx7FKa5HSpKn9FFibWYtwb2vzYa3pv1+dYuZi7hjHm5pahqvCZusIfsv9PiNemlOTwdIYe2bZFXCXScSlst7gxbLMcYF43iOEiNaSVbS+24tQngUWRqLkrofVAhb+WTYaaDrengHoMQ2H9UB+xX7gCH7FBQ+KtE2RXAwIANVB7T/9rnXicp+elnqZIglHH5+YBSTaenB3+Anl0mJlIk5csvpElJtQ96OK/aMWpYHFKS/kfISHOpctp4i639lbe5nNGhP2XyMUIEDlKgWeBplsgiW2RNOvgrj8psVYS4qSytkEN6skh0S3UuTuLEVxuTFK5fSUO8PgvZdua9biAXhq0/CLbqut1WsE1+1hP2HY9l8P/AlQtxGuY1GCgG28EKyOGW2FkZ+nHdVyyMeh9uCraAgCekm81p0XKM="
    # SONATYPE_PASSWORD:
    - secure: "FsCGugHltX8t92kMr+J2IrMUo72t+pBu/VIidxFB73yMASlhLczkP8GniY+ypCBhjizNj63o7rULgXg6OExb4RYG35Q2EDnI7TEKlfVLZdR5Qae1YB8K6laJLiFuC+aB0Bb0al2tfUYGD/sc9t5rVUr0k69dt/MA1aD/yx1iwWLZlARaRUgeO406Za1KufujcUNPMekJeDDm+CbKFTUPcXrqkxrXxZfZbrgtTeuuC2PRCqRmlPYA5N9Z0iD5lb6e05md+DwFmFBH8FYNPlTIqB9iw9hFQD53iCfvJjMTo+6lOedYtHK03WNUZcqTpokr/Icm2ZQ/zaHcaxQKpdb63lVxdZU+FaftqN43+WL4gBSuT43t/d/vBMeu5Up/dS1nIbKWR+WC9tTE3S4cigBGmvl0/hCtTWyCtN4mELTGGNc7xLMbHo+UxtPZLV42rJh1SCAcQ+XneTtEpUDC93XtewhvgUcaf/Pk2bbs28yzMhxevv1TreiXE007IvRbSpMeVhuYYQTypS8WHMHpD6Itxf4d8b46g0bW0YEDPjsOhbZnxhuUZpp7DP/2W7xqwZVm2Tt4lD7yRzOcg1mY4ZPkxb9LhWuW8AYm7JGpcFW3trb2az9FC0Y5Fhoa6TeXBF2zJZfY5PPjFABZW9OHeU2HIgDAYhk2CllQgwSFFwzlHeQ="
    # GPG_PASSPHRASE:
    - secure: "TSX/cX8qui4b6QPS053mzNBYcvjxS79Ugy7Mx5xVdvLiDw2OFT1K1oXXkG2WyJDaJIhZs0mwbc7sRfXHseZIqoAC+tist9OdYXtUXbZt83QYGb6FgVYUR08PXyK/Pv7MuDPJwh4DuJvmtiKaRAAhexD6zdddWrgqwXEsbGM8aVGagqeDUcoRBam27m5EiclZK7KymZhQ6TQdLyipW7tCb3cDhNzqWHqWsLsT3hXbTKWK6P+GTlhMjp/kW1GgLowmWRGniKqumRM8be07/kFdQ5iGP/ynSN6gxgqgDdT4CueyH0LD/wYocmFf57DIrouv11QnE3L14d/ofJlwFIypJdTWHh98Qy8DWt1p3WgXnrdsBekeiEsEpmRg1sGZGukfCig8rTKRER7fCWbl3/ggGXGuZAAy4PnPKlSJ/fvSJPqlmWQPe48h/iZ0xrcyBJo2YBsXuQHvtN7BbtfG1E+fiAXkBATJIZ3rF1144OozuS+FkwPqT4I+3GU70eR6qIbJZ6cbDnRh4BmkASavJ3TuE79svl1ZNAAbtrsTa+KRHiEBHfLPN9ak21T49pGKdBTZ9/X9TbBjIMuQhT4ILJ1wEegKkaqyXGbZGXbjxeyFRcqkAXn9JZXdOSz3ungjOYFFbh1gmLPT7bvfn4fZL7U+2QYcSBoNeoHblbynw6vYMlY="
    # ENCRYPTION_PASSWORD:
    - secure: "CuaLG83NybvyZcybA4D9E8H9NgVuEoJasDbKISWILd3LMsqPzldTYPb3OgaTHiHEXMRuARQxwiWYy7m4Be+TbAsheKettWUZNTQyhMLRAU7NT0iFXWWTTxRv5R6y6MlpZWOGkSSckZRT0DEW5RTCwJOXt5emMXMdNeRSz8pnO3OkPPBlpf+O1z+aQQZ7Te7zoALkshCby8WToaaetLBFX1ybYS8dMC0msU3gORD3hEk72VAkjvsMrzFbJBpfibbFb1kQSyIC//eqHevI8v5PZkxfEmFqsg8Cj79IxyH053n6F/dnpBwo14ouTKHOT6WNQC/bQvITuuHew1mU29bSHzoSMffbH/3ePXmVuCYsRKqwarW2WojMK+yziC1S8eFQLPvYw4jQvXaZDHMYBZvHWiko0w0wPCZWoxA1Vs/um41KrmuRXGgVvPqlX9oyBq/PhZ/4rTHRGn3ouy20fSDYEbdsRBXgZ+c6ozhYJyjJf8k1FWs1d1MZn3RVGpD/hqHTld64FmfjM2edNSSx59kiVGD1ZvGSluXuQ83aY51bvsUhaAeKho7BgdbanQnvf/kHRce4E+WG71s7uLWlepgg+HWGfMoSQJouayS3svKdbPheNqulKkoH+iMld5W/nMGlc0JjpIfNsQskYU3tX/K1kBzppoeHlhgPXeNbJHjdDo4="

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

cache:
  directories:
  - $HOME/.m2

before_install:
  - bash .travis/update_version.sh
  - bash .travis/decrypt_keys.sh

install: true

script: bash .travis/build.sh

after_success: bash .travis/remove_keys.sh

after_failure: bash .travis/remove_keys.sh

deploy:
  provider: releases
  api_key:
    secure: tB9NOvGsD09V8GgCoAWOdTl9///QdyKZKo00BMIk46R/6aYxr+bMTpoOXSp/1ni1uaU4rnZQCaVFTRXXNyCGpYIyZBI4jFPah2oSvuyy+y8dQCmr3b/LZQbfFQt7HK1Z5VjWMf5deu2Y7inRSXiyZF0g/U4a0ytS3OR76iCWo+HB1kIns4heP1tq5+3OCQJU0H01bRvwcoHOnHGaFKXs4sbAG/507oX5LW4FMhR+raeelTI83Qu0syaqDcfIWTl4vXr4Lu6lNNNoo+SwhiGhrpalrw7Vn1W2CB6SWtQU6D6qMTdQRAyZtPF/3Am0T2nRAdhARzN300Wr9rAEt0EJc4YgeFlxcPnFEDg6mbZFuwbzFTVkzErehrkzzcxx040ZI1eGSHV1E5GBWFClLOwU1Lrl3dxITtkjJ3kHKF9BtMAWRgIeBKOY4eG8Qh6omnxNlBkD6mG2zvZ2owhlNbuIl+qYmjHoznpI+Kq6+rgxI2gD7hbGqH3GkAKp+eB7Tw/wIOBoPOiUh5ZrDgKdriQvp7hMdoBf5Tyzeu/rqenW2QSQLTRXkTr/urYIwSxOx8FBfZc4LhGSSey8iBgdn4f1YMMubAXEW/QyMoN+QhRzNxj62m3xEuzOKRIq3Ffby+XOM3FKo6vuk1gAR8ELnemdOFEtOvb3w1+vxBys71SQbEs=
  file_glob: true
  file:
    - /home/travis/build/arturolszak/hycube-simulator/target/hycube-simulator*.jar
    - /home/travis/build/arturolszak/hycube-simulator/target/hycube-simulator*.zip
    - /home/travis/build/arturolszak/hycube-simulator/documentation/*
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8

after_deploy:

after_script: bash .travis/clean_after_script.sh
