language: java

env:
  global:
    - SONATYPE_USERNAME=hycube
    # SONATYPE_PASSWORD:
    - secure: "vR3YJRbVTnGs9eb3puFKPmShHJp2sQpF/v/nc7BlwFgdimgjbGQo2xrvV2KSsXaJODmL+CTP2XrDdEoheA+FukGub/nKrtoFbwKItBwgOKpY2OUTEAbKvpGrJvoOPNWm1DxXK6lVwTppi9oKl47z4tocdT42yLb1A3BaOzjZwRO9/4p8B3ZmuyJ/mWmmrNRLK9uEh6qQTn2txgAOMM/c/6g/+UL+9COBVVwLhsyQy00WXx/s2NZsBMctA1m+Opj4Ff8WUCVlqZ36x2NV/01bAxG7F12pJ+GhXBrl3wfEL7U9T9a2sz9rMgTIxvasAJrV43sE/ObEVqgk4PxTzUvcIxFr9blm4x/ayovpo2ISPYEwX6jInOmSCKTFtCpRdNAAROnl9oVGLMhtC7RDN+JI+22RWCfhc5bFKk1dRD89nMxUuYOj+o/yVAxjBLmD04y52wcfWfbPOezMeL+j170rM9OGbC1A6eTrj9KFN1cgbAioExBLNQozdl3fw3ZIMJLEZSUsQA8SgRx26z4+2zAhMQEOBOK25moRSiEKgCSEq3VG99IXVNgN5XVro682gwvHnuZXJqnJCkRTKc0jR20dFtSjbzT/ySTrz7ySDrdfVA/+lYGDnhoONpnsfxFQeZRldm0E53dh5zrtH1x2OEaef7LhrWXFuGDIQok9ek0ECLc="
    # GPG_PASSPHRASE:
    - secure: "pCV3sfXSzAGgVxxWmQ65OAhh7+qUWRcGgqOO0MovKmMs3iTKUW9arwQvMI5OP5ylOgqjTJ0fBmODH1W4VwCDC2Ae7HxO5E0exQ/p7kCmVzxTclhFikRcVbnfWD3VS5vIE8HPn0mCENTiVUv5py/cEk3wpIrrc5uGax07YtIRtCtoVcq4l15McFpykq693cxFG5bsXQGyU3TnMLPOhSEOe6XDRvdWkI7QGa/8cXGpCNUNDRFEKbHqGPUnjLwRAtWi3yAIEcCVFO577ColFAX2rMQm5HL3cIPVbbCyWJBOqbhuMhBR/eacOPR1RNNSfWrylTWvDctQmz6ISyEdRey+aLMnTUQkaNqaTGnapqY1QLzB0QIEU1DFLkAN2GQREAnoSXecPnG92wSXoE3zereS89PrcpFfDFZsnLI+t3Gk7EbVwE12bryu7RIX8+VKnqW6bAKKB7ooLBvxO7GKxZ2+AUC/ZH4dtHIYeo54Kb7cX/wMVxlIXxRiz7posjxnADzA7jYz2c/mp/sLaJRxTowALjhN/y7C5A3Fi8ck3vR9AlRf+uUNatsaNwv1iZw41u2xU5ci61FV3C2felxvvcmB5w9aB7XWNA0ztCGp3USPABwlcdhuhfhLgG2j38730JYDoUxWehMLV09qOxHfCYlmbdSpm7ZHBuq6wE/JuKNqwaw="
    # ENCRYPTION_PASSWORD:
    - secure: "Sj13nc2TtMYflsEKa8OoGAxFC+d4lSy+T7PNIj7XsityjVrHbeQr2elfrx5shFQzclCEz8B/9OdH1iKnV4hPE28f7dbg/fvMUvQbJyTRmq6CMut2udPb9O3e/gveUeYMaihk6gJvmuY0/iXyVUznjyS3x1jaSMYLsfvFAqIjbc8INqF8j1sWk51+ZHe3SoS5/DH2g3nCI2noBQF+iWtE+SgVMXBKAc99ccwG+3OBlbn6bnpgGK7Hko8L8hd4cvMsLVyO+p+DwFB++H4147NsC5IcByNK4GHpTtt2OIuXKqTVJjMGcqFH1huO3Bp2G6unNjVDR8t2rRgSRQeGsjn2uItHgOdKDa02LwK6gnShMsKUvSUv0hxSsRltlPFlp4Zs0OYmG6sYrxAyfqD1Xa4DK44hP+dJZ16MLyqG4DNd8OnOea079qUaZKexPe9SIG4FHC4zZ7hjaCMLcVEQwPhpvYYlyYu6KpCeHwRcs1wi1sL1PQ4wD3pAzZC7OZKrTbDujfUOera4YYMkhaABhpQKm3bHlaUQ/2LJ0x7XwBDnOWum6rjpm73Zn+ctzkY/Z/jzRfhj6FKuhqf7yHT8OZR5ShYP06xkhltZcyhOMJAFbdtcpIGnKjCZqZeHVrGore2OgRFW9luIgDYlxFJFKOEJ1AFW8vkaPdX7yQuLzmLfsMQ="

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

cache:
  directories:
  - $HOME/.m2

before_install:
  - bash .travis/update_version.sh
  - bash .travis/decrypt_keys.sh

install: true

script: bash .travis/build.sh

after_success: bash .travis/remove_keys.sh

after_failure: bash .travis/remove_keys.sh

deploy:
  provider: releases
  api_key:
    secure: tB9NOvGsD09V8GgCoAWOdTl9///QdyKZKo00BMIk46R/6aYxr+bMTpoOXSp/1ni1uaU4rnZQCaVFTRXXNyCGpYIyZBI4jFPah2oSvuyy+y8dQCmr3b/LZQbfFQt7HK1Z5VjWMf5deu2Y7inRSXiyZF0g/U4a0ytS3OR76iCWo+HB1kIns4heP1tq5+3OCQJU0H01bRvwcoHOnHGaFKXs4sbAG/507oX5LW4FMhR+raeelTI83Qu0syaqDcfIWTl4vXr4Lu6lNNNoo+SwhiGhrpalrw7Vn1W2CB6SWtQU6D6qMTdQRAyZtPF/3Am0T2nRAdhARzN300Wr9rAEt0EJc4YgeFlxcPnFEDg6mbZFuwbzFTVkzErehrkzzcxx040ZI1eGSHV1E5GBWFClLOwU1Lrl3dxITtkjJ3kHKF9BtMAWRgIeBKOY4eG8Qh6omnxNlBkD6mG2zvZ2owhlNbuIl+qYmjHoznpI+Kq6+rgxI2gD7hbGqH3GkAKp+eB7Tw/wIOBoPOiUh5ZrDgKdriQvp7hMdoBf5Tyzeu/rqenW2QSQLTRXkTr/urYIwSxOx8FBfZc4LhGSSey8iBgdn4f1YMMubAXEW/QyMoN+QhRzNxj62m3xEuzOKRIq3Ffby+XOM3FKo6vuk1gAR8ELnemdOFEtOvb3w1+vxBys71SQbEs=
  file_glob: true
  file:
    - /home/travis/build/arturolszak/hycube-simulator/target/hycube-simulator*.jar
    - /home/travis/build/arturolszak/hycube-simulator/target/hycube-simulator*.zip
    - /home/travis/build/arturolszak/hycube-simulator/documentation/*
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8

after_deploy:

after_script: bash .travis/clean_after_script.sh
