language: java

env:
  global:
    - SONATYPE_USERNAME=hycube
    # SONATYPE_PASSWORD:
    - SONATYPE_PASSWORD=fakepassword
#    - secure: "dnOxvALDxzUeiueR61d7gVWgf7u/t3PDLRF5Xs3UNB9WkKhhIBhePVMn0GEnbEeWKUBlH5wEAkdGSJhfwZWiD0qH6vvTQyzmCm+FiCMPabRxdKDvF9gLMcRIlCjvw0wxbT26Qn+UjGFjaYixJdNqPpoj+2Bcx9fkjq9jyGm01d5Y3psJNh//HLw9asOwvCzGd9Xpzlt2mGaXESxhqBYuX2/CJGQ07o9qG47HNBvV0Ubr6SFvGm3sfVMPJbhmZxe6j7iy2Nh7zNXUbawXLiLT0yJIExkKpJvKeMdUIJ2oaTsv4bBAvMKQYvuq7GipymZDBNr1NdCAVi0aNE9Ke6rtvk10dVhXYxwtBFwbaWWnpDmQtKGuluUTHsAfCwpKbqaMc29qYSD8jEHJEscXVtMsNSknOZrVbZBO21cyzZhKaSeugvCYsqvij54ESWLulqhjcxh8G4urUUYOkJN6X7sQBT1RIT6JQm7yaFuGLarQd7TEOnsIFeD+jijeLMsLxPXQlEBdnw5Ah4XGC7LnKCE+IiRbQB8rvsFHwE2sPLPmXDQEmt9wvDi2jizd231weO8c70RnpwZSHRcxXsKsWUUKSafwji9RLTx7WgXc01VYGqaouLZY+gTEvcOuuEwKrqGrht59dS3xqkrBTBxN73rHRiLP7+zcKJk09lcB76ASFQM="
    # GPG_PASSPHRASE:
    - secure: "lbSYzQNahhx6KRjpit4+pODnfXF9pRPWaHFvD+dETXva+2rOdzdee5wFC4A8r8nE1wc6dBqw2/pbWe3gfcFjk5SSky3eIKxlIe4PPYraZqfX4DvU3TKh4auAyURcnNDKnv3ouXwkSnILPYdxCrXrr3cZpOUBcLUz1W+ykSg1ii6cP77gcJOHP3ex3+VwxSED/g11lV41EQVc+21j68fftbkY3yqq/X8o/aMKwy1dWHee6V76yrVVBEUKdY7cSlsWvmS/SJW9MksdqRJ1KzUWPTYuRJhz2vJPYJVUPschOH1q6nMaydFi/Gh5ugPnWluIW2Q6iTY5KUwLH/LhmmKOHzcmsGtcLfFpRXYVVWGGcxs3siiM1rVF+ftdfKw7CzGhiVoKqp4ucvq9CmPX/F9vWFy0jm25HZEWbX2/Bo/2lKzoUo7QI3vh6Kjv8bXLZBedmdmAIxmmNqqBFk+pcJbc2KHoafVFI86saWqiHCtCafOTFf8a9aLhECaDmpE8kM/3iOzIvrlgtSZnjSPbrUYdC9tHrzBRvH5XddtFD+K2pvZ98fNJoqeXWDXZ1a97DrzsrwsNu1yishAmjUj4mcNSyQayaEUrMnvBXjAHnr6I4F3bP6H5RDMP6gwgd5FUJjdH3VzuH54hUIsLJOBOe+wfrpLFuJPH/5geXe7R2xMcOVs="
    # ENCRYPTION_PASSWORD:
    - secure: "Sj13nc2TtMYflsEKa8OoGAxFC+d4lSy+T7PNIj7XsityjVrHbeQr2elfrx5shFQzclCEz8B/9OdH1iKnV4hPE28f7dbg/fvMUvQbJyTRmq6CMut2udPb9O3e/gveUeYMaihk6gJvmuY0/iXyVUznjyS3x1jaSMYLsfvFAqIjbc8INqF8j1sWk51+ZHe3SoS5/DH2g3nCI2noBQF+iWtE+SgVMXBKAc99ccwG+3OBlbn6bnpgGK7Hko8L8hd4cvMsLVyO+p+DwFB++H4147NsC5IcByNK4GHpTtt2OIuXKqTVJjMGcqFH1huO3Bp2G6unNjVDR8t2rRgSRQeGsjn2uItHgOdKDa02LwK6gnShMsKUvSUv0hxSsRltlPFlp4Zs0OYmG6sYrxAyfqD1Xa4DK44hP+dJZ16MLyqG4DNd8OnOea079qUaZKexPe9SIG4FHC4zZ7hjaCMLcVEQwPhpvYYlyYu6KpCeHwRcs1wi1sL1PQ4wD3pAzZC7OZKrTbDujfUOera4YYMkhaABhpQKm3bHlaUQ/2LJ0x7XwBDnOWum6rjpm73Zn+ctzkY/Z/jzRfhj6FKuhqf7yHT8OZR5ShYP06xkhltZcyhOMJAFbdtcpIGnKjCZqZeHVrGore2OgRFW9luIgDYlxFJFKOEJ1AFW8vkaPdX7yQuLzmLfsMQ="

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install:
  - bash .travis/update_version.sh
  - bash .travis/decrypt_keys.sh
  - ls -l

install: true

script: bash .travis/build.sh

after_success: bash .travis/remove_keys.sh

after_failure: bash .travis/remove_keys.sh

deploy:
  provider: releases
  api_key:
    secure: vB0d2RdSz/o1qy56tqM+/vbAB7zpIJkYU/TWHhXYUbYDEEcPlseY1hpRYGSN09x0LHBLNpZSxfVPdwAagoAVWMC7YlSSJoV1W2vwicleILEywxGkZs0oB2xf200W78l43iYdnwWZa/PyihcsT+zWffiX3l0Th26Rs4AuPtWyMbBSABi1js0sR3Y036WBUF04NXaTig6fvvTZ+FEGLrRDTH6R+td2VJ4V7FlUV1FBMt3hMUfx0q3QFxdg1y5EQWPPXu3PFCcXKsU/ckK63ghJikn8N+R6Z9mPzkxbQZkuLbufAWww/a0BNc+UoyTbAbx3e5aMwNo6xyaymyKYDYdPCuGvddd1hgSMh+fDCxraXQLxemsT+fcHtc1ALrYc+ITtFGqagyS3zaodO+Jwvh7q13QRIjYyNVP76ivD7OBcWLvaVEe+AHcHudnocgBq58KGcPTXc9EaEdehdczmHE5lhEgkyuLAeieVmkX5kQvT0ciHv3BSiHTA2B5kjYy0+KvB8g0srr7ifBnT/d7IVL2NDoT8EntS2ZFrkUY1Dm/lsrm4Ho9e/FcZBZbPDsC+GAksUN6b96F438lWjUGHNM95KB9Ohno0+MCemD7onKU0ZM1x/K7CWez7wUp0gx0UQ8mARYvetp5BEBw/aD+L6Ms0ybcMVVlUqa9WcF8e36nssMs=
  file_glob: true
  file:
    - /home/travis/build/arturolszak/hycube-simulator/target/hycube-simulator*.jar
    - /home/travis/build/arturolszak/hycube-simulator/documentation/*
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8

after_deploy:

after_script: bash .travis/clean_after_script.sh
